import fs from 'fs';
import path from 'path';

// This is the centralized data fetcher that hooks up your Programmatic SEO pages
// to your actual data pipelines (scrapers or external APIs).

export async function getManagerPressureData(slug: string) {
  try {
    const dataPath = path.join(process.cwd(), 'data', 'manager_pressure.json');
    if (fs.existsSync(dataPath)) {
      const fileData = fs.readFileSync(dataPath, 'utf-8');
      const allManagers = JSON.parse(fileData);
      const manager = Array.isArray(allManagers) ? allManagers.find((m: any) => m.slug === slug) : allManagers[slug];
      if (manager) {
        return manager;
      }
    }
  } catch (error) {
    console.error("Failed to load real scraper data, falling back to dynamic generation:", error);
  }

  // Fallback programmatic generation based on slug if scraper data is missing
  const name = slug.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
  const hash = slug.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  
  return {
    name: name || "Manager",
    club: "Manchester United",
    pressureScore: 60 + (hash % 35),
    status: "Critical",
    trend: "up",
    sackingOdds: "2/1",
    recentResults: [
      { opponent: "Liverpool", result: "L", score: "0-3" },
      { opponent: "Brighton", result: "L", score: "1-2" },
      { opponent: "Fulham", result: "W", score: "1-0" },
    ],
    nextMatch: "Aston Villa (A)",
    sentiment: "-45% WoW",
    topGrievances: [
      "Tactical inflexibility in big games",
      "Poor talent identification in the transfer market",
      "Losing the dressing room"
    ]
  };
}

export async function getMatchupData(slug: string) {
  try {
    const dataPath = path.join(process.cwd(), 'data', 'matchups.json');
    if (fs.existsSync(dataPath)) {
      const fileData = fs.readFileSync(dataPath, 'utf-8');
      const allMatchups = JSON.parse(fileData);
      if (allMatchups[slug]) {
        return allMatchups[slug];
      }
    }
  } catch (error) {
    console.error("Failed to load real matchups data, falling back:", error);
  }

  const [teamA, teamB] = slug.split('-vs-').map(team => 
    team.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')
  );
  
  return {
    homeTeam: teamA || "Home Team",
    awayTeam: teamB || "Away Team",
    competition: "Premier League",
    kickoff: "TBA",
    venue: "Home Stadium",
    homeForm: ["W", "D", "L", "W", "W"],
    awayForm: ["L", "L", "D", "W", "L"],
    predictedFormation: {
      home: "4-3-3",
      away: "4-2-3-1"
    },
    keyBattle: {
      homePlayer: "Home Star",
      awayPlayer: "Away Star",
      metric: "Expected Goals (xG)",
      context: "Data pipeline currently updating matchup metrics."
    },
    tacticalTakeaway: "Matchup data is being generated by the tactical engine."
  };
}

export async function getPlayerData(slug: string) {
  try {
    const dataPath = path.join(process.cwd(), 'data', 'players.json');
    if (fs.existsSync(dataPath)) {
      const fileData = fs.readFileSync(dataPath, 'utf-8');
      const allPlayers = JSON.parse(fileData);
      const player = Array.isArray(allPlayers) ? allPlayers.find((p: any) => p.slug === slug) : allPlayers[slug];
      if (player) {
        return player;
      }
    }
  } catch (error) {
    console.error("Failed to load players data:", error);
  }
  return null;
}

export async function getLeagueData(slug: string) {
  try {
    const dataPath = path.join(process.cwd(), 'data', 'leagues.json');
    if (fs.existsSync(dataPath)) {
      const fileData = fs.readFileSync(dataPath, 'utf-8');
      const allLeagues = JSON.parse(fileData);
      const league = Array.isArray(allLeagues) ? allLeagues.find((l: any) => l.slug === slug) : allLeagues[slug];
      if (league) {
        return league;
      }
    }
  } catch (error) {
    console.error("Failed to load league data:", error);
  }
  return null;
}

export async function getAllPlayers() {
  try {
    const dataPath = path.join(process.cwd(), 'data', 'players.json');
    if (fs.existsSync(dataPath)) {
      return JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
    }
  } catch (error) {
    console.error("Failed to load players data:", error);
  }
  return [];
}

export async function getAllLeagues() {
  try {
    const dataPath = path.join(process.cwd(), 'data', 'leagues.json');
    if (fs.existsSync(dataPath)) {
      return JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
    }
  } catch (error) {
    console.error("Failed to load leagues data:", error);
  }
  return [];
}
