import fs from 'fs';
import path from 'path';

// This is the centralized data fetcher that hooks up your Programmatic SEO pages
// to your actual data pipelines (scrapers or external APIs).

export async function getManagerPressureData(slug: string) {
  // In a production environment, this would hit your database or a live API.
  // Example: return fetch(`https://api.yourdomain.com/managers/${slug}`).then(res => res.json());
  
  // For now, if you have a python scraper running on a cron job saving to a JSON file, 
  // you can read it directly like this:
  try {
    const dataPath = path.join(process.cwd(), 'data', 'manager_pressure.json');
    if (fs.existsSync(dataPath)) {
      const fileData = fs.readFileSync(dataPath, 'utf-8');
      const allManagers = JSON.parse(fileData);
      if (allManagers[slug]) {
        return allManagers[slug];
      }
    }
  } catch (error) {
    console.error("Failed to load real scraper data, falling back to dynamic generation:", error);
  }

  // Fallback programmatic generation based on slug if scraper data is missing
  const name = slug.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
  
  // Deterministic score based on slug so Google sees consistent content
  const hash = slug.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  
  return {
    name: name || "Manager",
    club: "Manchester United",
    pressureScore: 60 + (hash % 35), // Always 60-94, but consistent per slug
    status: "Critical",
    trend: "up",
    sackingOdds: "2/1",
    recentResults: [
      { opponent: "Liverpool", result: "L", score: "0-3" },
      { opponent: "Brighton", result: "L", score: "1-2" },
      { opponent: "Fulham", result: "W", score: "1-0" },
    ],
    nextMatch: "Aston Villa (A)",
    sentiment: "-45% WoW",
    topGrievances: [
      "Tactical inflexibility in big games",
      "Poor talent identification in the transfer market",
      "Losing the dressing room"
    ]
  };
}

export async function getMatchupData(slug: string) {
  try {
    const dataPath = path.join(process.cwd(), 'data', 'matchups.json');
    if (fs.existsSync(dataPath)) {
      const fileData = fs.readFileSync(dataPath, 'utf-8');
      const allMatchups = JSON.parse(fileData);
      if (allMatchups[slug]) {
        return allMatchups[slug];
      }
    }
  } catch (error) {
    console.error("Failed to load real matchups data, falling back:", error);
  }

  // Similar logic for pulling real matchup data from your pipeline.
  // Example: return fetch(`https://api.yourdomain.com/matchups/${slug}`).then(res => res.json());

  const [teamA, teamB] = slug.split('-vs-').map(team => 
    team.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')
  );
  
  return {
    homeTeam: teamA || "Home Team",
    awayTeam: teamB || "Away Team",
    competition: "Premier League",
    kickoff: "TBA",
    venue: "Home Stadium",
    homeForm: ["W", "D", "L", "W", "W"],
    awayForm: ["L", "L", "D", "W", "L"],
    predictedFormation: {
      home: "4-3-3",
      away: "4-2-3-1"
    },
    keyBattle: {
      homePlayer: "Home Star",
      awayPlayer: "Away Star",
      metric: "Expected Goals (xG)",
      context: "Data pipeline currently updating matchup metrics."
    },
    tacticalTakeaway: "Matchup data is being generated by the tactical engine."
  };
}
